### ISSUE TITLE
SQL Server (msql) formatting not working inside cells

### ISSUE THREAD

**Issue by RedEyedDog** [cmoog/vscode-sql-notebook#24] opened 2022-03-21 14:05 UTC
Hi

I have the SQL Server extension im trying to format the cells but nothing is happening.

Is formatting supported?

Thanks

**Comment by cmoog** [comment] 2022-03-22 01:25
If you have a SQL formatter installed through a different extension, `Format Cell` should work as expected from the command pallet. Otherwise, it might be appropriate to add built-in support to `vscode-sql-notebook` so users get this built-in.

**Comment by RedEyedDog** [comment] 2022-03-22 10:09
Do you need help with that.. i could do it. But i have only recently started looking at custom vscode extensions.. might need some direction

**Comment by cmoog** [comment] 2022-03-22 18:59
I'd be happy to accept a contribution with added support for formatting. The npm module [sql-formatter](https://www.npmjs.com/package/sql-formatter) looks like it could be a good path forward.

**Comment by RedEyedDog** [comment] 2022-03-23 12:02
I have forked the code and will investigate :) i think it should first try and use the default formatter the user has if they have one and if not offer to install one?

**Comment by cmoog** [comment] 2022-03-23 22:00
After some further testing, I think it is a deficiency in `ms-mssql.mssql` that prevents it from working when SQL files are opened as notebooks. When testing `adpyke.vscode-sql-formatter`, the `Format Cell` command pallet action works just as expected.

So, seeing as this is not a bug fixable in `vscode-sql-notebook`, I'm going to close this issue. We can open a new issue to track integration of [sql-formatter](https://www.npmjs.com/package/sql-formatter) as an embedded format provider exposed by this extension.

**Closed by cmoog** 2022-03-23 22:00 UTC
Labels: bug
